@startuml
autonumber
skinparam style strictuml
skinparam maxMessageSize 150
actor "Registered User" as ActorUser

box "NGO System" #LightCyan
    participant "Security UI" as UI
    control "Security Controller" as Ctrl
    entity "User" as UserEnt
    entity "OTPVerification" as OTPEnt
    entity "Notification" as NotifEnt
end box

ActorUser -> UI : requestReset(email)
activate UI
UI -> Ctrl : processReset(email)
activate Ctrl

Ctrl -> UserEnt : findByEmail(email)
activate UserEnt
UserEnt --> Ctrl : userObj
deactivate UserEnt

Ctrl -> OTPEnt : generateOTP(userObj.userId)
activate OTPEnt
OTPEnt --> Ctrl : otpObj
deactivate OTPEnt

Ctrl -> NotifEnt : sendOTPNotification(email, otpObj.code)
activate NotifEnt
NotifEnt --> Ctrl : success
deactivate NotifEnt

Ctrl --> UI : promptOTP()
deactivate Ctrl
UI --> ActorUser : "Check Email"
deactivate UI
@enduml
